-d C:\Users\AkimovMA\Desktop\DIP_SEM\proj\FPGA-PLK\encoder_spi\impl\gwsynthesis\encoder_spi.vg
-p GW2AR-18C-QFN88-8
-pn GW2AR-LV18QN88C8/I7
-cst C:\Users\AkimovMA\Desktop\DIP_SEM\proj\FPGA-PLK\encoder_spi\src\encoder_spi.cst
-cfg C:\Users\AkimovMA\Desktop\DIP_SEM\proj\FPGA-PLK\encoder_spi\impl\pnr\device.cfg
-bit
-tr
-ph
-sdf
-ibs
-vccaux 3.3
-posp
-o
-ovhd
-warning_all
-tt
-timing
-cst_error
-no_cst_warning
-correct_hold 1
-route_maxfan 23
-global_freq 100.000
