-d C:\Users\AkimovMA\Desktop\plis\encoder_spi\impl\gwsynthesis\encoder_spi.vg
-p GW2AR-18C-QFN88-8
-pn GW2AR-LV18QN88C8/I7
-cst C:\Users\AkimovMA\Desktop\plis\encoder_spi\src\encoder_spi.cst
-cfg C:\Users\AkimovMA\Desktop\plis\encoder_spi\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
-global_freq 100.000
